In [3]:
import numpy as np

import logging 
import traceback
import numpy as np 

logging.basicConfig(filename="log_file.log",level=logging.INFO,format='%(asctime)s %(levelname)s %(message)s')

Question 1:

In [11]:
class inclusive:
    
    def __init__(self,arr):
        
        self.arr = arr
        
    def array(self):
        """
        Reconstructing the permutation perm
        
        """
        try:
            values = []
            mini = 0
            maxe = len(self.arr)

            for i in self.arr:
                if i == 'I':
                    values.append(mini)
                    mini += 1
                else:
                    values.append(maxe)
                    maxe -= 1
            return (values + [maxe])
        
            logging.info('Successfully Reconstructed the permutation perm')

        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
            
            
a = inclusive("IDID")
a.array()

[0, 4, 1, 3, 2]

Question 2:

In [208]:
class matrix:
    
    def __init__(self,arr,target):
        
        self.arr = arr
        self.target = target
        
    def find_target(self):
        """
        Return True if target in the given array
        
        """
        try:
            
            for i in range(len(self.arr)):

                if self.target in self.arr[i]:
                    return True

            return False
        
            logging.info('Successfully Returned True if target in the given array')

        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
    
a = matrix([[1,3,5,7],[10,11,16,20],[23,30,34,60]],3)
a.find_target()

True

Question 3:

In [213]:
class mountain:
    
    def __init__(self,arr):
        
        self.arr = arr
        
    def array(self):
        """
        Return Mountain Array or not
        
        """
        try:
            
            arr = list(self.arr)
            
            index = arr.index(max(self.arr))

            inc = arr[:(index)+1]

            dec = arr[index:]


            if len(inc) > 1  and len(dec) > 1:
                if inc == sorted(inc) and dec == sorted(dec,reverse = True):
                    for i in range(len(arr)):
                        if i <= arr.index(max(arr)):
                            if inc.count(inc[i]) == 1:
                                continue
                            else:
                                break

                        else:
                            if dec.count(arr[i]) == 1:
                                continue
                            else:
                                break
                    return True

                else:
                    return (False)

            else:
                return (False)
            
            logging.info('Successfully Returned Mountain Array or not')

        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
        
        
        
a = mountain(np.array([1,4,6,5,3]))
a.array()

True

Question 6:

In [276]:
class array:
    
    def __init__(self,input_array):
        
        self.input_array = input_array
        
    def rotate (self):
        """
        Returns original or empty array if its doubled or otherwise
        
        """
        try:
            
            doubled = []

            if len(self.input_array) % 2 == 0:

                for i in range(len(self.input_array)//2):

                    if self.input_array[i] * 2 not in self.input_array[len(self.input_array)//2:]:
                        break

                    else:

                        doubled.append(self.input_array[i])

            return doubled

            logging.info('Returns original or empty array if its doubled or otherwise')
            
        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
        
    
    
a = array(np.array([1,3,4,2,6,8]))
a.rotate()

[1, 3, 4]

Question 7:

In [767]:
mat = np.ones((3,3),dtype = int)
a = 0

while a < 3:

    for i in range(len(mat)):
        for j in range(len(mat)):
            val = []
            if i == 0:
                mat[i][j] = j+1

            if i != 0 and j == len(mat)-1:
                mat[i][j] = (mat[0][len(mat)-1])+i

            if i == len(mat)-1 and j != len(mat)-1:
                val.append(mat[i][len(mat)-1])
                mat[i][-j+i-1] = max(val) + j+1
            
                
            elif i != len(mat)-1 and j == 0:
                val.append(mat[len(mat) -1][j])
                mat[-i+len(mat)-1][0] = max(val) + i
                
            elif i != 0 and i != len(mat) -1 and j != 0 and j != len(mat) -1:
                if i == 1:
                    val.append(mat[i][0])
                    mat[i][j] = max(val) + j

                else:
                    val.append(mat[1][len(mat)-2])
                    mat[i][len(mat)-j-1] = max(val)+j
                    


            
    a += 1
print(np.squeeze(np.asarray(mat)))

[[1 2 3]
 [8 9 4]
 [7 6 5]]
