Question 1:

In [1]:
import numpy as np

In [2]:
import logging 
import traceback

logging.basicConfig(filename="log_file.log",level=logging.INFO,format='%(asctime)s %(levelname)s %(message)s')


class sum_of:
    
    def __init__(self,input_array,target):
        
        self.input_array = input_array
        self.target = target
        
    def sum_of_input_array(self):
        """
        Returns the indexes of numbers which sums upto target value
        
        """
        try:
            for i in range (0,len(self.input_array)):
                if self.input_array[i] != self.target:
                    add = 0
                    for j in range (1,len(self.input_array)):
                        add = self.input_array[i]+self.input_array[j]
                        if add == self.target:
                            if i < j:
                                return np.array([i,j])

                                logging.info('Successfully returned the indexes')
                                
                        else:
                            continue
                else:
                    return np.array([i])
                
        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())

            
inputt = np.array([2,5,8,1])
a = sum_of(inputt,6)
a.sum_of_input_array()

array([1, 3])

Question 2:

In [3]:
class removal:
    
    def __init__(self,input_array,target):
        
        self.input_array = input_array
        self.target = target
        
    def remove_target(self):
        """
        Returns an array after Replace the target variable with "_"
        
        """
        try:
            inputt = []
            for i in self.input_array:
                input_array = list(self.input_array)
                if i != self.target:
                    inputt.append(i)
            inputt.append(("_"))
            
            return np.array(inputt)
        
            logging.info('Successfully returned an array without target variable')
            
            
        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())



    
a = removal(np.array([4,6,5,7,2,3,7,7,7]),7)
a.remove_target()

array(['4', '6', '5', '2', '3', '_'], dtype='<U11')

Question 3:

In [4]:
class index:
    
    def __init__(self,input_array,target):
        
        self.input_array = input_array
        self.target = target
        
    def index_target(self):
        """
        Return an index of the target variable 'to be' or is positioned
        
        """
        try:
            for i in range(0,len(self.input_array)):

                if self.input_array[i] == self.target:
                    return i

                if self.target not in self.input_array:

                    if self.input_array[i] > self.target:
                        if self.input_array[i-1] < self.target:
                            return i

                    if self.input_array[i] < self.target and i == len(self.input_array) - 1:
                        return (i+1)

                    elif self.input_array[i] > self.target and i == 0:
                        return i 
                    
                logging.info('Successfully returned an index of the target variable')
                    
        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())


            
            
a = index([1,6,12,22,34],21)
a.index_target()

3

Question 4:

In [5]:
class add:
    
    def __init__(self,input_array):
        
        self.input_array = input_array
        
    def add_one (self):
        """
        Returns +1 incremented integer in a list
        
        """
        try:
            
            input_ = list(self.input_array)

            if input_[-1] != 0 and input_[-1] + 1 != 10:
                index = input_[-1]
                del input_[-1]
                input_.append(index+1)
                return np.array(input_)

            else:
                return ("last digit shouldn't be 0")
            
            logging.info('Returned the incremented list')
                    
        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
        
        
a = np.array([3,5,5])
c = add(a)
c.add_one()

array([3, 5, 6])

Question 5:

In [6]:
class arrays:
    
    def __init__(self,array_1,array_2,m,n):
        
        self.array_1 = array_1
        self.array_2 = array_2
        self.m = m
        self.n = n
        
    def append(self):
        """
        Arrays are merged and sorted
        
        """
        try:
            
            _1_array = list(self.array_1)
            _2_array = list(self.array_2)

            index =  len(_1_array) - len(_2_array)

            return np.array(sorted(_1_array[:index] + _2_array))

            logging.info('Returned sorted array')

        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
     
        

a = arrays(np.array([1,2,3,0]),np.array([2]),3,3)
a.append()

array([1, 2, 2, 3])

Question 6:

In [7]:
class count:
    
    def __init__(self,input_array):
        
        self.input_array = input_array
        
    def count_int(self):
        """
        Return True or False based on the value occurences
        
        """
        
        try:
            input_ = list(self.input_array)

            for i in input_:

                count_ = input_.count(i)

                if count_ == 2:

                    return True

                else:

                    count_ = 0
                    continue

            if count_ == 0:

                return False
            
            logging.info('Returned sorted array')

        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
            
            
                          
                        
a = count(np.array([1,5,5,1]))
a.count_int()

True

Question 7:

In [8]:
class arr:
    
    def __init__(self,input_array):
        
        self.input_array = input_array
        
    def Zero(self):
        """
        Return an array consisting of 0's at the end
        
        """
        try:
            count = 0

            for i in range(len(self.input_array)):
                if self.input_array[i] != 0:
                    self.input_array[count],self.input_array[i] = self.input_array[i] , self.input_array[count]
                    count += 1

            return self.input_array

            logging.info('Returned an assorted array of 0"s at the end')

        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
            
            
a = arr(np.array([1,0,4,0,5,5,0,0,12,4]))
a.Zero()

array([ 1,  4,  5,  5, 12,  4,  0,  0,  0,  0])

Question 8:

In [9]:
class missing:
    
    def __init__(self,input_array):
        
        self.input_array = input_array
        
    def repeat_miss(self):
        """
        Returns an array with the repititive number and the missing value.
        
        """
        try:
            
            input_ = self.input_array

            rang = np.arange(input_[0],input_[len(input_)-1]+1)

            output = []

            for i in range(len(input_)):

                count = list(input_).count(input_[i])

                if count == 2:
                    if input_[i] not in output:
                        output.append(input_[i])

                if rang[i] not in input_:
                    output.append(rang[i])

            return (np.array(output))
            logging.info('Returned an array with the repititive number and the missing value.')

        except Exception as e:
            logging.error("Exception occurred", traceback.format_exc())
    
    
a = missing(np.array([1,2,2,3,4,4,5,6,9]))
a.repeat_miss()

array([2, 4, 7, 8])